HHS81/c182s

- Systems/indicated-airspeed.xml
- Systems/init-instrumentation.xml
- c182s-set.xml
- c182s.xml
I think this is correct. I did a pull to make sure I have all the latest changes. It showed I was getting changes but when I tried to merge them there were non from master to master. So I think this is the most current (master) base.
I'm pretty sure the problem was a duplicate indicated-airspeed.xml call in c182\c182s.xml
See #134
> Bug #134 Console error

- gui/dialogs/aircraft-dialog.xml
- gui/dialogs/securing.xml
Closes #139 
Changing radios into checkboxes on securing and aircraft dialogs.
Note that the ground-equipement dialog is fine, since the radio there is used to select under which wing the stairs will be put (only one option can be selected)
> Radios to checkboxes in dialogs

- Nasal/c182s-electrical.nas
- Systems/instrumentation.xml
This PR fix Issue#164 and change the heading indicator to a vacuum driven one.
> Issue 164: wrong heading-indicator type

- Systems/fuel.xml
I think for a top fuel tank system the zero-g cutoff must occur relatively near to 0 g. -0.5g is way too much it seems.
> FuelSystem: Corrected negative G-forces cutoff to real zero gravity

- gui/dialogs/c182s-baggage-weight.xml
Added the POH placard text to the baggage GUI.
I think it would also be great to make the placard resolution in the texture good enough to be read in game from the walker.
> Added placard text to baggage door GUI

- Models/Instruments/Avionics/kn62a.xml
Switching off the KN62A DME was not possible.
> Fix KN62a DME Power button (switch off was not possible)

- c182s-sound.xml
The ICS dial was too loud; this PR adjusts the volume to comply with the other dials.
> Fix GMA dial rotation sound volume

- Nasal/kn62a.nas
When the DME unit power-switch was switched to off, but GMA panel DME-Ident is on, the ident code was played.
I think the Ident should stop, when the DME is switched off, however.
This PR introduces a small nasal handler to the existing DME code that handles this.
> Made DME ident stop when DME power is switched off

- Nasal/c182s.nas
Currently we can have strange effects when tiedowns are in place and the plane gets in the air.
This can happen for example, if the user presses STRG+U when tied down or (possibly, however already accounted for!) at in-air-starts.
When the Plane is more than 10ft in the air, the tiedowns are automaticly removed now.
(A short test just for fun showed that we need ~65 knots 90° to make the wind force dominate the tiedown force -> e.g. plane lifts off and tiedowns tear shortly after that)
> Remove tiedowns when in the air

- Models/Instruments/ManPressFuelFlow.xml
- Models/Instruments/egt.xml
- Models/Instruments/fuelqty.xml
- Models/Instruments/oil.xml
- Systems/engine.xml
- Systems/fuel.xml
- Systems/instruments.xml
- c182s-set.xml
Fixed the fuel quantity an oil-tem/press gauges to not show indication without power.
@HHS81 @gilbertohasnofb 
Before merge i have questions:
- Should the VAC EGT and CHT gauges behave the same? (i think so, as they surely are electrically driven too?)
- What about ManPress? I suppose (like in "guess") this is mechanically driven?
> Fix #223 (Fuel gauge always "on")

- Nasal/c182s-states.nas
- Nasal/c182s.nas
- c182s-set.xml
- gui/dialogs/aircraft-dialog.xml
- states/approach-overlay.xml
- states/auto-overlay.xml
- states/cruising-overlay.xml
- states/idling-overlay.xml
- states/parking-overlay.xml
Now it is possible to init state from command line: add for example "`--prop:/sim/start-state=cruising`"
This is very useful in combination with `--vc=120` and gui-launcher setting "on final approach..." to practise landings
- Refactored state-code a little
- state "ColdAndDark" is now always before preflight (secured and with fuel contamination and without oil/fuel checked
> State additions

- Models/Instruments/Avionics/gma340.xml
Additional fix for PR #235 (Issue #137): Added material animation to light marker lights in GMA.
Marker lights where dark in night with glareshield lighting on.
> Added material animation to light marker lights in GMA

- Models/Instruments/Avionics/gma340.xml
- Models/Instruments/Avionics/gma340properties.xml
- Nasal/gma340.nas
- c182s-set.xml
GMA340: Enhanced marker handling
- marker is now silent, when audio panel is inoperable or shut off
- marker can be temporarily muted now like described in manual (press "mkr-mute" once when marker-beacon is sounding)
- Fix for lighting of beacon-indicators when GMA is powered off
> GMA-340: enhance marker handling

- c182s-set.xml
- states/saved-overlay.xml
> Fix #271 (add "saved" state overlay so it gets selectable in new launcher)

- states/cruising-overlay.xml
- states/idling-overlay.xml
- states/parking-overlay.xml
- states/saved-overlay.xml
I corrected the descriptions text to comply to the launcher items.
No big deal, just documentatory.
the saved state was "broken" when called from command line (it was accidentally called "Saved" instead of the lowercase variant)
> Made state overlays comply to new launcher

- c182s.xml
Currently i have the following, made up numbers (depending on density and speed; here at ~130kt):
- open door =~ 30Knots
- open window =~10 Knots
I don't know if numbers are realistic but the effect is noticeable and easily to adjust if needed.
> Fix #275: add drag when doors/windows are open

- Models/interior-model.xml
- Nasal/c182s.nas
- c182s-set.xml
- gui/dialogs/aircraft-dialog.xml
Solved Issue #290 
New is also a little addition that helps in temperature management.
If heating/cooling to a greater extent, it will be incorporated in the text and also on the tooltip of the air/heat levers.
> Issue290 - new Option to disable temp texts; new indication of heating/cooling

- Models/c182s.xml
- Models/interior-model.xml
- Nasal/c182s-states.nas
- Nasal/c182s.nas
- Systems/ground-effects.xml
- c182s-set.xml
- c182s-sound.xml
- c182s.xml
Open from PR #278 was the following:
Should we port over the other two functions as well, or reimplement them in a simpler nasal approach, or skip alltogether?
> Correct door drag numbers and force-close doors in flight (remainder from pr #278)

- Models/Instruments/Avionics/kx165-1.xml
- Models/Instruments/Avionics/kx165-2.xml
- Nasal/c182s-states.nas
- Systems/electrical.xml
The reason was that the `power-btn` property was changed only by turning the knob.
However other scripts (like Red Griffin ATC) rely on it to get the "radio is turned on"-state.
The power-btn of com1/2 is now calculated and considered "on" when not only the knob is turned,
but also the radio is serviceable and has electrical power.
> Refactored calculation of COM1/2 radio power-btn to electrical.xml

- Nasal/engine.nas
- Systems/electrical.xml
- Fix 2020.02 startup error complaining about missing `electrical/output/comm[n]` nodes
- Fix nasal magnetos selector error (was cosmetical)
> Small fixes for 2020.2

- Nasal/davtron803.nas
I rechecked the LCD display of the davtron and temperature should not read out fractions but just whole degrees.
> Adjusted davtron temperature display to round numbers (no fraxtions) as per manual

- Nasal/c182s-states.nas
(fixes getting stuck with overlay cold&dark)
> Fix #337: Apply chocks only when their state differ 

- Nasal/c182s-electrical.nas
- Nasal/c182t-electrical.nas
- Systems/electrical.xml
Operating the flap actuators as well as turning on radio lights or glareshield consume electrical power, showing on the ammeter
> Issue 343 flaps operation + lights consume power

- Documentation.md
- Nasal/damage.nas
- Nasal/engine.nas
- Systems/external-heat.xml
- Systems/fuel.xml
- Systems/propulsion.xml
- c182s-set.xml
- c182t-set.xml
- gui/dialogs/aircraft-dialog.xml
This adds simulation of spark plug icing (enable it in the aircraft dialog!)
Spark plug icing will prevent starting of the engine. It can occur if the engine does not get warm enough, ie. if it dies in cold weather directly after starting.
When this occurs the spark plugs are frozen over, because the water product from the combustion will condensate on the still-freezingly cold plugs and thus short the electric gap which normally provides the spark to ignite the fuel.
It can be remedied by applying preheater to melt the ice, but this takes a long time usually.
It's way better to take precautions (eg preheat the engine if it is below freezing temperatures).
(fix #274)
> Simulate spark plug icing

- Systems/KAP140.xml
<s>- [ ] Enforce BARO setting after startup sequence</s>
<s>- [ ] (maybe: implement startup sequence after PWR-ON? we could do that pretty simple probably with an Nasal/Canvas combo)</s>
<s> -[ ] fix oszillation when heading INBOUND to a VOR </s>(see: #372)
> KAP-140: Fixes

- Models/interior-model-c182s.xml
- Models/interior-model-c182t.xml
- Nasal/c182s.nas
- c182s-set.xml
- c182t-set.xml
- gui/dialogs/aircraft-dialog.xml
Over the past years I had the issue (here and there) that i had the yoke hidden to be able to read the instruments/knobs for takeoff and sometimes I was not centered by accident which gave bad takeoffs.
Today this idea struck my mind and I think it improves the user experience alot, since now we are able to see the stuff behind the yoke _and_ being able to see where the yoke is :grin: 
Users might tune the transparency setting to their liking (between fully-transparent to fully-opaque), and the setting is saved and restored across sessions.
----
> Optional transparent yoke-hiding for c182s/t

- c182s-set.xml
- c182t-set.xml
Adds keybinds `CTRL+4/6` to adjust rudder trim
> Fix #431: Add keybind for rudder trim

- Documentation.md
- Models/Human/copilot.xml
- Models/Human/humans-pax-parachuters.xml
- Models/Human/pax0.xml
- Models/Human/pax1.xml
- Models/Human/pax2.xml
- Models/c182-submodels.xml
- Models/c182s.xml
- Models/c182t.xml
- Models/interior-model-c182s.xml
- Models/interior-model-c182t.xml
- Nasal/c182s.nas
- Systems/cabin-heat_and_air.xml
- Systems/sounds.xml
- c182s-set.xml
- c182s-sound.xml
- c182s.xml
- c182t-set.xml
- c182t.xml
- gui/dialogs/aircraft-dialog.xml
With the option enabled, seats, right door and yoke are removed.
When clicking on the passengers, they will jump out.
Alternatively all can be dropped at once using the "Jump!" button
from the aircraft options menu.
Fix #440
> Add skydiving option

- Documentation.md
- Nasal/engine.nas
- Systems/engine.xml
- Systems/propulsion.xml
- Tutorials/sparkPlugFouling.xml
- c182s-set.xml
- c182t-set.xml
- gui/dialogs/aircraft-dialog.xml
**Adding Spark plug fouling**
- Detailed spark plug fouling engine simulation
- Insim Tutorial to show the effect and how to avoid/mitigate
- [Documentation.md](https://github.com/HHS81/c182s/blob/Issue-439_SparkPlugFouling/Documentation.md#complex-engine-procedures) updated
- Added roughness if one magneto has failed
A overly rich mixture or idling on the ground for too long with cold combustion will foul your spark plugs, making the engine run rough. At the engine run up, the magneto check will reveal fouled plugs. There is a procedure to clear fouled plugs.
----
**Internals:**
- The engine coughing functionality was refactored in a generic "rough engine" implementation. Now the nasal part is very generic and mostly modelled in engine.xml and propulsion.xml. In the future, new "rough …
> Implement Spark plug fouling

- Engines/engIO540AB1A5.xml
- Nasal/c182s-states.nas
- Nasal/c182t-EISPublisher.nas
- Systems/engine.xml
- Systems/external-heat.xml
- Systems/instruments.xml
- Systems/propulsion.xml
- Tutorials/sparkPlugFouling.xml
- c182s-set.xml
- c182t-set.xml
Cold oil will now more slowly build pressure.
- oil pressure depending on viscosity
- viscosity depending on oil grade and oil temp
:point_up: Potentially can support switching oil grades in the future! :)
---
**Sources**
- POH 4-21:
- POH 8-14:
- 15W-50 viscosity specs: https://www.mobil.com/en-us/passenger-v ... il-1-15w50
- 15W-40 viscosity courve: https://wiki.anton-paar.com/us-en/engine-oil/
- some real life reports suggesting the current simulation is somewhat realistic (takes some time (minutes in very cold weather) where the needle moves slowly): http://www.cessna172club.com/forum/ubbthreads.php?ubb=showflat&Number=102858
> Better oil pressure simulation

- c182s.xml
- c182t.xml
Adding the jsbsim hooks to support AI wake turbolence.
MP wake turbolence is currently not supported by fgfs, but probably can be expected to use the same hooks in the future.
(Fix #462)
> Add AI wake turbolence

- Models/c182s.xml
- Models/c182t.xml
This way the trim wheel is lit and can be seen in the dark
The light is controlled mainly by the pedestal light knob but also affected by the glareshield and dome lights.
Fix #476
> Add pedestal light as compositor light spot.

- Systems/als-lights.xml
- Systems/instruments.xml
- c182s-set.xml
- c182t-set.xml
At nighttime, the radio stack and instrument lighting should briefly illuminate the cabin.
The current effect was so faint, that it was not visible in most cases.
Therefore this commit makes the effect a little more prominent.
Also, the radio stack lighting was not correct:
- the COM radios were not adressed correctly and thus never added light to the mix
- Some equipment is not lit when the radio stack light knob is off
- COM units should have a bigger effect on brightness than other equipment (it has more red lights)
> Fixes/tewaks for radio stack / instrument lighting

- Nasal/c182s.nas
FGCamera compatibility added
- Door will be opened when the walker exits the plane, if not yet open
fix #497
> Add FGCamera compatibility

- Models/Instruments/hi.xml
- c182s-set.xml
- c182t-set.xml
DG/HI: add "align" property, so knob does not rotate with precession
This is based on FGF SF ticket 2838 (https://sourceforge.net/p/flightgear/codetickets/2838/) for the precession to actually apply to the DG.
If applied, should be compatible to PR https://github.com/HHS81/c182s/pull/527
Also, this is downward compatible to older versions, so could be applied also without the SF ticket already.
Fix #525
> Issue525 save dg offset (by storing offset with simple DG implementation)

- Documentation.md
- Models/Instruments/Compass.xml
- Models/Instruments/ai-gauge.xml
- Models/Instruments/hi.xml
- Nasal/c182s-states.nas
- Nasal/c182s.nas
- Systems/instrumentation.xml
- Systems/instruments.xml
- c182s-set.xml
- c182t-set.xml
- gui/dialogs/aircraft-dialog.xml
This switches the heading indicator to the `heading-indicator-dg` implementation which is more powerful and realistic.
:warning: PR is based on switching to the DG based heading indicator, and only works with the patch to the core:
https://sourceforge.net/p/flightgear/codetickets/2839/
:information_source: Regarding the movement-errors, there is discussion on the mailing list if this is realistic:  https://sourceforge.net/p/flightgear/mailman/flightgear-devel/thread/6e66f08e3fb3f02a9d5c557cfd7a2910%40hallinger.org/#msg53245268
My impression is, that there should be no permanent movement related errors, as the gyro should move relatively freely due to the two axis bearing.
regarding to the videos:
- Uncaged maneuver limits are (for air driven): +-55° in pitch or roll (two videos below say …
> Issue525 save dg offset (by switching instrument to <heading-indicator-dg>)

- Systems/fuel.xml
Added a dedicated function modelling the "mixture unit". This now simulates the aux fuel pump enriching the mixture slightly (POH 7-28). (value is guessed because of lack of footage; but the effect is considered to be small, the chosen value is 1% richer mixture which yields a faint effect in the sim).
Also refactored the "is the fuel pump operating" switches in the fuel system file to a dedicated switch, to make the other switches more readable.
> Aux fuel pump enrichens mixture a bit

- Documentation.md
- Nasal/c182s-electrical.nas
- Nasal/c182t-electrical.nas
- Nasal/custom-failures.nas
- Systems/engine.xml
- c182s-set.xml
- c182t-set.xml
- gui/dialogs/aircraft-dialog.xml
- gui/dialogs/c182-extendedFailures.xml
The simulation is very basic, but I think good enough for that usecase.
You can crank the engine about 30 seconds (depending on OAT) before the starter melts.
The POH starter cycle (10s crank, 20s cooldown; then repeatable 2 times, then cooldown for 10 mins) is OK in warm weather (however not anymore in _very_ hot temps!).
It's implemented optional (-> aircraft menu) and defaults to off.
Fix #567
> Starter overheating simulation

- Systems/propulsion.xml
The complex engine simulation has some friction caluclation based on oil temps and viscosity, always getting the prop to a full halt in time. Without the complex simulation there was no friction at all. With a dead engine there needs to be some (internal engine) friction to make the prop also stop in time.
fix #578
> Added static friction on low RPM

- gui/dialogs/aircraft-dialog.xml
- gui/dialogs/c182-about.xml
- gui/dialogs/c182-documentation.xml
- gui/dialogs/c182-extendedFailures.xml
- gui/dialogs/c182s-baggage-weight.xml
- gui/dialogs/c182s-fuel-selector.xml
- gui/dialogs/c182s-fuel-strainer.xml
- gui/dialogs/c182s-left-fuel-drain.xml
- gui/dialogs/c182s-left-fuel.xml
- gui/dialogs/c182s-oil.xml
- gui/dialogs/c182s-right-fuel-drain.xml
- gui/dialogs/c182s-right-fuel.xml
- gui/dialogs/c182s-states.xml
- gui/dialogs/c182s-wheel-nose.xml
- gui/dialogs/damage-overview.xml
- gui/dialogs/fuel.xml
- gui/dialogs/ground-equipement.xml
- gui/dialogs/immat.xml
- gui/dialogs/securing.xml
- Adding "X" to the dialog close button in the windows header
- Added "Documentation" button to "about" dialog, which displays the content of the local Documentation.md file
> Issue 580 / Dialog header closing button: "X" Added

- Models/Instruments/CompassCorrectionCard.xml
Adding a "zoom function" to the compass correction card.
Clicking it will show a canvas dialog with a better readable card, so the pilot does not need to zoom into the card manually (wich I feel is tedious).
> Compass correction card: Zoom via canvas dialog
