Models/interior-model.xml

Hobbs-meter got the right scale, but wasn't at the correct position.
This should fix it.
Needs a new ELT anyway.
Signed-off-by: HHS81 <Heiko.H.Schulz@gmx.net>

Fix Issue #40 by placing the instrument at the correct position

---

Systems/als-lights.xml
c182s-set.xml

ALS landing and taxi lights
Closes https://github.com/HHS81/c182/issues/94

ALS landing and taxi lights

---

Models/interior-model.xml

throttle mixture and prop are now clickable (click and drag and also scrollable using mouse wheel)
Closes https://github.com/HHS81/c182/issues/96

throttle mixture and prop are now clickable

---

README.md

credits to wlbragg and other alterations to README

credits to wlbragg

---

README.md
c182s-set.xml

adding rating

---

c182s-set.xml

external shadow default as true

---

c182s-set.xml

inverting scroll direction

---

Systems/KAP140.xml
Systems/fuel.xml

Fix #168: I ported the current c172 Autopilot and it works really nicely now.

Fix autopilot

---

Models/Instruments/oil.xml
Nasal/engine.nas
Systems/engine.xml
Systems/fuel.xml
c182s-set.xml

Adjusted oil numbers and added some small features

Oil refinements

---

c182s-set.xml
c182s.xml
gui/dialogs/aircraft-dialog.xml

The winter kit reduces cooling airflow, helping keeping the engine warm at cold weather.

Added winterization kit (decreases cooling airflow -> higher temps)

---

Nasal/c182s-electrical.nas
Systems/electrical.xml

this PR fixes the electrical system:
no cranking, no lights and no avionics below 22V
battery capacity now also depends on outside temperature

Electrical fix of Issue#43

---

Models/Instruments/hi.xml

Fixed #203 
@HHS81 I'm unsure about the projects policy for such minor fixes - can i merge that directly into master? Do you insist on making a PullRequest for such things, or when is it okay to push directly to master?

Fix #203: make HI compass consistent to other dials

---

Models/c182s.xml
Systems/electrical.xml
Systems/indicated-airspeed.xml

Checklist item 2check pitot tube to be warm to the hand at 30secs max" can now be executed.

Added pitot warming "feelable" by hand

---

Models/Instruments/hi.xml
c182s-sound.xml

I fixed the issue #148 using a separate click sound.

Fix #148 (Add sound to HI offset dial)

---

Nasal/c182s-electrical.nas

Fix of Issue #212, bug had been introduced by me.

Fix Issue #212, bug was introduced by me

---

Models/c182s.xml

- Clickspot should not be available when propeller spins
- Fix clickspot visible from inside view

Fix winterkit clickspot

---

Models/Instruments/Avionics/kt76c.xml
Nasal/kt76c.nas
c182s-set.xml

Add property /instrumentation/transponder/factory-vfr-code to let user change VFR-Buttons code.

Add property /instrumentation/transponder/factory-vfr-code

---

Models/Effects/c182sreflect-uber.eff
Models/Immat/immat.xml
Models/interior-model.xml
c182s-set.xml

Fix of immat and annunciator panel flashlight effects path (see https://github.com/HHS81/c182s/pull/259#issuecomment-366349262)

Issue248 flashlight effect on annunciator panel and immat

---

Models/Effects/shadow.xml
Systems/c182s-ground-effects.xml

Fixes #250 
Implemented this on the c172p as well.

No shadow when aircraft is upside-down (fix #250)

---

Nasal/c182s-states.nas
Systems/fuel.xml
Systems/propulsion.xml

Fix #273 
Also makes autostart/checklists adjust mixture to altitude

Fix issue273

---

Nasal/c182s.nas

Fixed Isse #280 bis commenting out not needed code which introduced this bug

Fix Issue #280

---

Engines/engIO540AB1A5.xml
Models/Effects/c182_enginesmoke.xml
Nasal/engine.nas
Systems/engine.xml
Systems/propulsion.xml
c182s-set.xml

Another fix for the isse #279.
Also adds two minor new features:
- very hot oil burns now (higher consumption rate)
- very old oil leads to some friction (above idle)

Fix #279 (engine dies when in idle)

---

Nasal/c182s-states.nas

In branch https://github.com/HHS81/c182s/tree/Issue-292

Fix #292 (adjust winter kit on state change depending on OAT)

---

Models/Instruments/Avionics/kt76c.xml
Nasal/c182s-electrical.nas
Nasal/kt76c.nas
Systems/instrumentation.xml
gui/dialogs/aircraft-dialog.xml

I enhanced the KT76c transponder:
- a little better performance demanding
- TST mode fully implemented
- "R" reply annunciator behaves correctly now (blink/steady/off, depending on mode and power)
- Multiplayer compatible to ATCPie

KT76c multiplayer and enhancements

---

Systems/fuel.xml

Ported over from the c182t branch, still works on FGFS Version 2018.3.2 (i currently have no fresher install), can please someone verify?

Fix for #315

---

Models/Instruments/Avionics/gma340.xml
Models/Instruments/Avionics/gma340properties.xml
Nasal/gma340.nas
c182s-set.xml
gui/dialogs/aircraft-dialog.xml

Add integration of FGCom, so it is controllable from the GMA-340 audio panel and reacts to loss-of-power/failures

FGCom integration with GMA 340 audio panel

---

Nasal/engine.nas

This adds a little eye candy effect: the plane shakes a little when the engine fires.

Plane shakes a little when engine ignites

---

Models/interior-model-c182s.xml
Models/interior-model-c182t.xml
Nasal/c182s.nas
c182s-set.xml
c182t-set.xml

Its compatible with default view offset!
It's persited and restored next time!

Allow (persistent) adjust pilot seat position

---

Models/Instruments/Avionics/kap140/KAP140TwoAxisAlt.xml
Models/Instruments/Avionics/kt76c.xml

Implemented knobs pushing animation for
- Transponder
- Autopilot

Knobs pushing

---

Nasal/c182s.nas
gui/dialogs/c182-about.xml
gui/dialogs/c182s-menu.xml

- Reordered menus to be similar to C172 (esp. for new pilots changing from there)
- Added nice abouts dialog

Small Menu additions/changes

---

Models/Human/copilot.xml
Models/Human/humans.xml
Models/Human/pax0.xml
Models/Human/pax1.xml
Models/Human/pax2.xml
Models/c182s.xml
Models/c182t.xml
Systems/pax.xml
c182s-set.xml
c182t-set.xml

Passengers and Copilot for the C182S / C182T :grin: 
- Easily turned off with the standard "show pilot" checkbox in the standard view dialog.
- Only shown if the seats are occupied in the loading dialog.
Ready for merge in my view.

Added Passenger and Copilot models

---

c182s-set.xml
c182t-set.xml

Would be a good thing to have this consistent across different planes :)
Ready for merge

Allow lowercase "y" to show/hide yoke (conformance to c172 and others)

---

Nasal/c182s-states.nas
gui/dialogs/aircraft-dialog.xml
states/approach-overlay.xml
states/auto-overlay.xml
states/cruising-overlay.xml
states/idling-overlay.xml
states/parking-overlay.xml
states/saved-overlay.xml

- Fix #287
- Fix #399
- take-off and cruising state now fast-boot the new KAP140 autopilot
- "saved" now has a better viewing display in launcher

Fix Issues 287 399 (state system fixes/additions)

---

Models/Effects/c182sreflect-uber.eff
Models/c182s.xml
Models/c182t.xml
Nasal/c182s-multiplay.nas
c182s-set.xml
c182t-set.xml

Adding "slow MP properties" (TDM encoded string) for not so important props.

Added MP slow properties

---

Tutorials/winterFlying.xml
c182s-set.xml
c182t-set.xml

Add winter flying tutorial.

---

Documentation.md
Nasal/c182s.nas
Nasal/custom-failures.nas
Nasal/engine.nas
Systems/engine.xml
Systems/fuel.xml
Systems/propulsion.xml
Systems/static-sources.xml
Tutorials/winterFlying.xml
gui/dialogs/c182s-extendedFailures.xml

Fixes a typo (ammount->amount)

Fix 456: Typo ammount->amount

---

Nasal/damage.nas
Systems/damage.xml
c182s-set.xml
c182s-sound.xml
c182s.xml
c182t-set.xml
c182t.xml

Implement Flap damage due to overspeed

---

Systems/damage.xml

Revise gear breakage side force

---

Models/Instruments/Avionics/kap140/kap140-properties.xml
Models/Instruments/Avionics/kap140/kap140-proprules.xml
Models/Instruments/Avionics/kap140/kap140.xml
Nasal/kap140.nas
c182s-set.xml
gui/dialogs/kap140-dlg.xml

Refactored KAP140 to more easily interface with external hardware etc
fix #492

Issue 492: kap140 update

---

Systems/engine.xml
Systems/propulsion.xml
Tutorials/winterFlying.xml
c182s-set.xml
c182t-set.xml
gui/dialogs/c182s-oil.xml

Add SAE 30 oil for cooler weather operations

More oil grades

---

Models/Instruments/vor/vor.xml
Models/Instruments/vor/vor2.xml

Revise NAV needle deflections

---

Nasal/c182s-states.nas

Was already tested systematically

Issue542 state apply engine fix

---

Nasal/c182t-electrical.nas

The FG1000 was not operable when the avionics master was off.
But the C182T has an "essential bus" which is linked to the battery circuit; thus it should power the PFD even with avionics-switch-1 off.

C182T: FG1000 wired to new essential bus

---

Models/Instruments/hi.xml
Models/Instruments/ki227_228.xml

Heading should be given as 0=360.
See https://sourceforge.net/p/flightgear/codetickets/2874/

Heading tooltips unified 0->360

---

Models/interior-model-c182s.xml
Models/interior-model-c182t.xml
c182s.xml
c182t.xml

Ported Octal450 input filtering from PA28

---

Models/c182s.xml
Models/c182t.xml
c182-sound-multiplayer.xml

Remote C182's have engine sound now.
fix #587

Add multiplayer sounds

---

Nasal/kt76c.nas

Also made internal code now behave like "manual button presses", so internal variables get set better; for example when pressing the VFR button or restoring saved code.
Fix #594

KT76C Transponder: Fixed bug with Test mode and partial codes

---

Models/interior-model-c182s.xml
Models/interior-model-c182t.xml

Implement nicer animation for parking brake lever

---

Models/Instruments/Compass.xml
Systems/instruments.xml

Needs SF ticket merged: https://sourceforge.net/p/flightgear/codetickets/2904/
fix #599

Magnetic Compass: Switched to exposed magnetic compass props for simulating roll and pitch axis
